import type { PassengerData } from "./types";

export const passengerDatabase: PassengerData = {
    'RN4A7B': {
        name: 'RUWAYD NAIF AYED ALMGHAMISI',
        nameEn: 'RUWAYD NAIF AYED ALMGHAMISI',
        flight: 'SV154',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '12A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
    },
    'SM8K2L': {
        name: 'SAYIL MASAD SALIH AL-JOHANI',
        nameEn: 'SAYIL MASAD SALIH AL-JOHANI',
        flight: 'SV287',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '15C',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'MH9P3Q': {
        name: 'MUJHANAD SOHEI AHMAD HAYGAH',
        nameEn: 'MUJHANAD SOHEI AHMAD HAYGAH',
        flight: 'SV412',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '8B',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'MO5T6Y': {
        name: 'MONEEB OMAR ALLUHAYBI',
        nameEn: 'MONEEB OMAR ALLUHAYBI',
        flight: 'SV633',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '22F',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'NS7U8I': {
        name: 'NAIF SALEH FARAJ ALHARBI',
        nameEn: 'NAIF SALEH FARAJ ALHARBI',
        flight: 'SV789',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '5A',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'HA1O2P': {
        name: 'HAMZAH AZIZ KHLAF ALHARFI',
        nameEn: 'HAMZAH AZIZ KHLAF ALHARFI',
        flight: 'SV156',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '18D',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
     'RB3A4S': {
        name: 'RAED BANDAR SAEED ALSAUD',
        nameEn: 'RAED BANDAR SAEED ALSAUD',
        flight: 'SV445',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '11B',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'AM6D7F': {
        name: 'ABDUL MAJEED HASSAN JABER MAJHALY',
        nameEn: 'ABDUL MAJEED HASSAN JABER MAJHALY',
        flight: 'SV298',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '25E',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'FA8G9H': {
        name: 'FAHAD ALI ALHAZMI',
        nameEn: 'FAHAD ALI ALHAZMI',
        flight: 'SV567',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '14C',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'MS0J1K': {
        name: 'MOHAMMED SALMAN MDAHHE ALMUTAIRI',
        nameEn: 'MOHAMMED SALMAN MDAHHE ALMUTAIRI',
        flight: 'SV723',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '9A',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'MK2L3M': {
        name: 'MOAD KHALID NAJI',
        nameEn: 'MOAD KHALID NAJI',
        flight: 'SV834',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '7B',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'NH4N5O': {
        name: 'NAIF HAMMAD MUSALLAM ALNEMARI',
        nameEn: 'NAIF HAMMAD MUSALLAM ALNEMARI',
        flight: 'SV456',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '20F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'AA6P7Q': {
        name: 'ATYAF ADEL ABDULLAH ALDHAMADI',
        nameEn: 'ATYAF ADEL ABDULLAH ALDHAMADI',
        flight: 'SV189',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '16A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'SA8R9S': {
        name: 'SHATHA ABDULRAHMAN ALGAMDI',
        nameEn: 'SHATHA ABDULRAHMAN ALGAMDI',
        flight: 'SV345',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '13D',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'RM0T1U': {
        name: 'RITAL MOHAMMED ABUALJADAIL',
        nameEn: 'RITAL MOHAMMED ABUALJADAIL',
        flight: 'SV678',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '21B',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'SS2V3W': {
        name: 'SARAH SALEH M ALHARBI',
        nameEn: 'SARAH SALEH M ALHARBI',
        flight: 'SV234',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '19C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'RA4X5Y': {
        name: 'RAHAF MOHAMMED ABDULLAH ALASMARI',
        nameEn: 'RAHAF MOHAMMED ABDULLAH ALASMARI',
        flight: 'SV512',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '6E',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'AO6Z7A': {
        name: 'AMASI OMAR BAUWAYBIR',
        nameEn: 'AMASI OMAR BAUWAYBIR',
        flight: 'SV789',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '17F',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'AS8B9C': {
        name: 'ASAYIL ALI ABDULLAH ALQUZAYZ',
        nameEn: 'ASAYIL ALI ABDULLAH ALQUZAYZ',
        flight: 'SV623',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '10A',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'TA0D1E': {
        name: 'TALA AHMAD BAKR AQEEL',
        nameEn: 'TALA AHMAD BAKR AQEEL',
        flight: 'SV445',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '23D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'DR2F3G': {
        name: 'DALAL RUDDAH ALMUTANI',
        nameEn: 'DALAL RUDDAH ALMUTANI',
        flight: 'SV356',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '4B',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'RB4H5I': {
        name: 'RAHAF BANDAR ATI ALHARBI',
        nameEn: 'RAHAF BANDAR ATI ALHARBI',
        flight: 'SV154',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '24A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'RS6J7K': {
        name: 'RENAD SALEM ALJOHANI',
        nameEn: 'RENAD SALEM ALJOHANI',
        flight: 'SV287',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '10C',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'AZ8L9M': {
        name: 'ABEER ZAYED SULAIMAN ALAWRANI',
        nameEn: 'ABEER ZAYED SULAIMAN ALAWRANI',
        flight: 'SV412',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '3F',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'AO0N1P': {
        name: 'AHAD OUDAH ALBALAWI',
        nameEn: 'AHAD OUDAH ALBALAWI',
        flight: 'SV633',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '1A',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    }
};

export const occupiedSeatsForFlight = [
    '12B', '15A', '8C', '22D', '5B', '18E', '11C', '25F', '14A', '9B', '7C', '20A', '16B', '13E', '21C', '19A', '6F', '17A', '10B', '23E', '4C', '24B', '10D', '3A', '1B'
];


export function findPassenger(bookingRef: string, name: string) {
    const passenger = passengerDatabase[bookingRef.toUpperCase()];
    if (passenger && passenger.name.toUpperCase() === name.toUpperCase()) {
        return passenger;
    }
    return null;
}
