
import type { PassengerData } from "./types";

export const passengerDatabase: PassengerData = {
    'S8K2L1': {
        name: 'Abdulrahman Al-Srysri',
        nameEn: 'Abdulrahman Al-Srysri',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '1A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 1, weight: 23 }
    },
    'M9P3Q2': {
        name: 'Ali Al-Harbi',
        nameEn: 'Ali Al-Harbi',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '2A',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'O5T6Y3': {
        name: 'Bandar Al-Qizayz',
        nameEn: 'Bandar Al-Qizayz',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '3B',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'N7U8I4': {
        name: 'Fawzi Milibari',
        nameEn: 'Fawzi Milibari',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '4A',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'A1O2P5': {
        name: 'Ghazi Mugharbel',
        nameEn: 'Ghazi Mugharbel',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '5C',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'B3A4S6': {
        name: 'Rami Temraz',
        nameEn: 'Rami Temraz',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '6A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'M6D7F7': {
        name: 'Sultan Aldosari',
        nameEn: 'Sultan Aldosari',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '7A',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A8G9H8': {
        name: 'Turki Basamad',
        nameEn: 'Turki Basamad',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '8A',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S0J1K9': {
        name: 'Yahya Al-Johani',
        nameEn: 'Yahya Al-Johani',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '9C',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'K2L3M0': {
        name: 'ABDUL MAJEED HASSAN JABHER MAJHALY',
        nameEn: 'ABDUL MAJEED HASSAN JABHER MAJHALY',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '10A',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'H4N5O1': {
        name: 'ABDUL MJEED BASHEER ALANAZI',
        nameEn: 'ABDUL MJEED BASHEER ALANAZI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '11A',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A6P7Q2': {
        name: 'ABDULAZIZ ADNAN ALI ALYMANY',
        nameEn: 'ABDULAZIZ ADNAN ALI ALYMANY',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '12C',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S8R9S3': {
        name: 'ABDULLAH DAKHIL ALRABIEII',
        nameEn: 'ABDULLAH DAKHIL ALRABIEII',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '13A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R0T1U4': {
        name: 'ABDULHADI AHMED ALI ALSHAMRANI',
        nameEn: 'ABDULHADI AHMED ALI ALSHAMRANI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '14B',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'S2V3W5': {
        name: 'ABDULHANIN SAAD ABU SUWAYYID',
        nameEn: 'ABDULHANIN SAAD ABU SUWAYYID',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '15D',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        specialAssistance: 'wheelchair'
    },
    'R4X5Y6': {
        name: 'ABDULLELAH AWAAD ALHARTHI',
        nameEn: 'ABDULLELAH AWAAD ALHARTHI',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '16C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A6Z7A7': {
        name: 'ABDULMUIN MOHAMED ABDULMUIN ALSHARIF',
        nameEn: 'ABDULMUIN MOHAMED ABDULMUIN ALSHARIF',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '17B',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'S8B9C8': {
        name: 'ABDULRAHMAN EHAB AHMED ABDULGANI',
        nameEn: 'ABDULRAHMAN EHAB AHMED ABDULGANI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '18A',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'T0D1E9': {
        name: 'ABDULRHMAN OSAMA ABDULWAHAB KHALIL',
        nameEn: 'ABDULRHMAN OSAMA ABDULWAHAB KHALIL',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '19B',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'D2F3G0': {
        name: 'ABEER ZAYED SULAIMAN ALAMRANI',
        nameEn: 'ABEER ZAYED SULAIMAN ALAMRANI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '20B',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R4H5I1': {
        name: 'AHAD ABDULLAH ALAMRI',
        nameEn: 'AHAD ABDULLAH ALAMRI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '21A',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R6J7K2': {
        name: 'AHAD DHIAB ALATAWI',
        nameEn: 'AHAD DHIAB ALATAWI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '22A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Z8L9M3': {
        name: 'AHAD OUDAH ALBALAWI',
        nameEn: 'AHAD OUDAH ALBALAWI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '23A',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'O0N1P4': {
        name: 'AHMAD HAMZA ISMAIL RAMADI',
        nameEn: 'AHMAD HAMZA ISMAIL RAMADI',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '24D',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'A1B2C3': {
        name: 'AHMED EHAB AHMED ABDUL ATTI',
        nameEn: 'AHMED EHAB AHMED ABDUL ATTI',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '25A',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'D4E5F6': {
        name: 'AHMED ESSA ALI MAHDI',
        nameEn: 'AHMED ESSA ALI MAHDI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '26A',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'G7H8I9': {
        name: 'ALANOUD MOHAMMED HADIH HADADI',
        nameEn: 'ALANOUD MOHAMMED HADIH HADADI',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '27A',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'J0K1L2': {
        name: 'ALHANOUF ABDULLAH MOHAMMED ALSAQAR',
        nameEn: 'ALHANOUF ABDULLAH MOHAMMED ALSAQAR',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '28A',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'M3N4O5': {
        name: 'ALHANOUF MUHAMMAD ALANAZI',
        nameEn: 'ALHANOUF MUHAMMAD ALANAZI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '29A',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'P6Q7R8': {
        name: 'ALI HUSSEIN AL-SHEIKHI',
        nameEn: 'ALI HUSSEIN AL-SHEIKHI',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '30A',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S9T0U1': {
        name: 'AMANI MARZOUQ ALBAQAMI',
        nameEn: 'AMANI MARZOUQ ALBAQAMI',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '1B',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'V2W3X4': {
        name: 'AMAR MOHAMMED ALHARBI',
        nameEn: 'AMAR MOHAMMED ALHARBI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '2B',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Y5Z6A7': {
        name: 'AMASI OMAR BAJUWAYBIR',
        nameEn: 'AMASI OMAR BAJUWAYBIR',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '3C',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'B8C9D0': {
        name: 'ARWA AHMED MOBARKI',
        nameEn: 'ARWA AHMED MOBARKI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '4B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E1F2G3': {
        name: 'ASAIL MNSOUR ALZAHRANI',
        nameEn: 'ASAIL MNSOUR ALZAHRANI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '5D',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'H4I5J6': {
        name: 'ASAYIL ALI ABDULLAH ALQUZAYZ',
        nameEn: 'ASAYIL ALI ABDULLAH ALQUZAYZ',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '6B',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'K7L8M9': {
        name: 'ASEEL SALEM ALARAWL',
        nameEn: 'ASEEL SALEM ALARAWL',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '7D',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'N0O1P2': {
        name: 'ATYAF ADEL ABDULLAH ALDHAMADI',
        nameEn: 'ATYAF ADEL ABDULLAH ALDHAMADI',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '8B',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'Q3R4S5': {
        name: 'AZAH ABDULLAH ALSHEHRI',
        nameEn: 'AZAH ABDULLAH ALSHEHRI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '9D',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'T6U7V8': {
        name: 'AZZAM AYMAN ALSOBHI',
        nameEn: 'AZZAM AYMAN ALSOBHI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '10E',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        specialAssistance: 'wheelchair'
    },
    'W9X0Y1': {
        name: 'BADER AHMED SAEED ALGHAMDI',
        nameEn: 'BADER AHMED SAEED ALGHAMDI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '11D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Z2A3B4': {
        name: 'BADER MAMDOH HASAN BUGIS',
        nameEn: 'BADER MAMDOH HASAN BUGIS',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '12E',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'C5D6E7': {
        name: 'BAYADIR YASIR M ALMUWALLAD',
        nameEn: 'BAYADIR YASIR M ALMUWALLAD',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '13B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'F8G9H0': {
        name: 'BAYAN IBRAHIM EID ALATAWI',
        nameEn: 'BAYAN IBRAHIM EID ALATAWI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '14D',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'I1J2K3': {
        name: 'BASSAM IBRAHIM MOHAMMED',
        nameEn: 'BASSAM IBRAHIM MOHAMMED',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '15E',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'L4M5N6': {
        name: 'DALAL RUDDAH ALMUTANI',
        nameEn: 'DALAL RUDDAH ALMUTANI',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '16D',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'O7P8Q9': {
        name: 'EBTIHAL SADDIG SALEH JASTANIEH',
        nameEn: 'EBTIHAL SADDIG SALEH JASTANIEH',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '17C',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R0S1T2': {
        name: 'EMAD HAMAD MOHAMMED SALEM',
        nameEn: 'EMAD HAMAD MOHAMMED SALEM',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '18B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'U3V4W5': {
        name: 'EMAN ATALAH ALBALAWI',
        nameEn: 'EMAN ATALAH ALBALAWI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '19D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'X6Y7Z8': {
        name: 'EMAN MOHAMMED ALBALAWI',
        nameEn: 'EMAN MOHAMMED ALBALAWI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '20C',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A9B0C1': {
        name: 'ESRAA SALEH HASSAN',
        nameEn: 'ESRAA SALEH HASSAN',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '21D',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'D2E3F4': {
        name: 'EYAD AZIZ MUSLIM ALJUHANY',
        nameEn: 'EYAD AZIZ MUSLIM ALJUHANY',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '22B',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'G5H6I7': {
        name: 'FAHAD ALI ALHAZMI',
        nameEn: 'FAHAD ALI ALHAZMI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '23B',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'J8K9L0': {
        name: 'FAHHAH AYED ALHMMAD',
        nameEn: 'FAHHAH AYED ALHMMAD',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '24C',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'M1N2O3': {
        name: 'FAISAL FAHAD AHMED ALKHANBASHI',
        nameEn: 'FAISAL FAHAD AHMED ALKHANBASHI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '25B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'P4Q5R6': {
        name: 'FAISAL HAMAD ALLAHYANI',
        nameEn: 'FAISAL HAMAD ALLAHYANI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '26B',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S7T8U9': {
        name: 'FAISAL MOHAMMED ABDULLAH ALZUWAYID',
        nameEn: 'FAISAL MOHAMMED ABDULLAH ALZUWAYID',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '27B',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'V0W1X2': {
        name: 'FAISAL SALEM HASSAN ALZAHRANI',
        nameEn: 'FAISAL SALEM HASSAN ALZAHRANI',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '28B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Y3Z4A5': {
        name: 'FIRAS MOHAMMED ABDU',
        nameEn: 'FIRAS MOHAMMED ABDU',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '29B',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'B6C7D8': {
        name: 'GHADAH NAYF AL-BALAWI',
        nameEn: 'GHADAH NAYF AL-BALAWI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '30B',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E9F0G1': {
        name: 'GHAIDA MASSAD ALJOHANI',
        nameEn: 'GHAIDA MASSAD ALJOHANI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '1E',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'H2I3J4': {
        name: 'GHALA MOSAAED AL-JUHANI',
        nameEn: 'GHALA MOSAAED AL-JUHANI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '2E',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'K5L6M7': {
        name: 'GHASSAN SAUD HAMID ALKHUDAYDI',
        nameEn: 'GHASSAN SAUD HAMID ALKHUDAYDI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '3E',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'N8O9P0': {
        name: 'HADEEL ALI EBRAHIM HAKAMI',
        nameEn: 'HADEEL ALI EBRAHIM HAKAMI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '4E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Q1R2S3': {
        name: 'HADEEL OBAID ALSULAMI',
        nameEn: 'HADEEL OBAID ALSULAMI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '5E',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'T4U5V6': {
        name: 'HALAH SALEEM SALEEM ALMASOUDI',
        nameEn: 'HALAH SALEEM SALEEM ALMASOUDI',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '6E',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'W7X8Y9': {
        name: 'HANIN SAAD MOHAMMED ALZAHRANI',
        nameEn: 'HANIN SAAD MOHAMMED ALZAHRANI',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '7E',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'Z0A1B2': {
        name: 'IBRAHIM ABDULRAHMAN ALHAMDI',
        nameEn: 'IBRAHIM ABDULRAHMAN ALHAMDI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '8E',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'C3D4E5': {
        name: 'IBRAHIM ABDULSHAFI SALEH ATTIAH',
        nameEn: 'IBRAHIM ABDULSHAFI SALEH ATTIAH',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '9E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'F6G7H8': {
        name: 'IBRAHIM NASEER ABDULLAH',
        nameEn: 'IBRAHIM NASEER ABDULLAH',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '10F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'I9J0K1': {
        name: 'IBRAHIM SALEEM MVALHEJAILI',
        nameEn: 'IBRAHIM SALEEM MVALHEJAILI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '11E',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'L2M3N4': {
        name: 'JANA SALEH ALI ALSHIKH',
        nameEn: 'JANA SALEH ALI ALSHIKH',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '12F',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'O5P6Q7': {
        name: 'JOUD MOHAMMED NASSER ALMUTAE',
        nameEn: 'JOUD MOHAMMED NASSER ALMUTAE',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '13F',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'R8S9T0': {
        name: 'JOUD OMAR SULEIMAN ALBALAWI',
        nameEn: 'JOUD OMAR SULEIMAN ALBALAWI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '14E',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'U1V2W3': {
        name: 'KHALID ABDULLAH HINDI',
        nameEn: 'KHALID ABDULLAH HINDI',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '15F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'X4Y5Z6': {
        name: 'KHALID YASEN ABDULLAH ALSHKHAI',
        nameEn: 'KHALID YASEN ABDULLAH ALSHKHAI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '16E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A7B8C9': {
        name: 'KHULUD MUHANNA ALJOHANI',
        nameEn: 'KHULUD MUHANNA ALJOHANI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '17D',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'D0E1F2': {
        name: 'LAMA HAMED SAAD ALSHMRANI',
        nameEn: 'LAMA HAMED SAAD ALSHMRANI',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '18F',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'G3H4I5': {
        name: 'LAYALI FAYEZ ALZARRA',
        nameEn: 'LAYALI FAYEZ ALZARRA',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '19E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'J6K7L8': {
        name: 'MAJD MAZEN HAROUN BAFANA',
        nameEn: 'MAJD MAZEN HAROUN BAFANA',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '20D',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'M9N0O1': {
        name: 'MAJED MASHNI MOSA ALZAHRANI',
        nameEn: 'MAJED MASHNI MOSA ALZAHRANI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '21E',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'P2Q3R4': {
        name: 'MALEK AHMED ZAYED ALTHAQAFI',
        nameEn: 'MALEK AHMED ZAYED ALTHAQAFI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '22C',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S5T6U7': {
        name: 'MALAK IBRAHEM AL-MASLMANE',
        nameEn: 'MALAK IBRAHEM AL-MASLMANE',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '23F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'V8W9X0': {
        name: 'MADA HASSAN N ALAMRI',
        nameEn: 'MADA HASSAN N ALAMRI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '24E',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Y1Z2A3': {
        name: 'MANAL SALEM EID ALBALAWI',
        nameEn: 'MANAL SALEM EID ALBALAWI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '25C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'B4C5D6': {
        name: 'MARAM MOHAMMED AHMED ALODAYSANI',
        nameEn: 'MARAM MOHAMMED AHMED ALODAYSANI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '26C',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E7F8G9': {
        name: 'MAY BADR HAMZA MUBARAK SAYED',
        nameEn: 'MAY BADR HAMZA MUBARAK SAYED',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '27C',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'H0I1J2': {
        name: 'MESHAL OUDAH SALMAN ALHAWITI',
        nameEn: 'MESHAL OUDAH SALMAN ALHAWITI',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '28C',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'K3L4M5': {
        name: 'METEB ABDULLAH E ALGETHAMI',
        nameEn: 'METEB ABDULLAH E ALGETHAMI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '29C',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'N6O7P8': {
        name: 'MOAD KHALID NAJI',
        nameEn: 'MOAD KHALID NAJI',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '30C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Q9R0S1': {
        name: 'MOHAMMED SALMAN MDAHHE ALMUTAIRI',
        nameEn: 'MOHAMMED SALMAN MDAHHE ALMUTAIRI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '1D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'T2U3V4': {
        name: 'MONEEB OMAR ALLUHAYBI',
        nameEn: 'MONEEB OMAR ALLUHAYBI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '2D',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'W5X6Y7': {
        name: 'MUUHANAD SOHEI AHMAD HAYGAH',
        nameEn: 'MUUHANAD SOHEI AHMAD HAYGAH',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '3D',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Z8A9B0': {
        name: 'MUNERAH SALEEM M ALFAIDI',
        nameEn: 'MUNERAH SALEEM M ALFAIDI',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '4D',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'C1D2E3': {
        name: 'NAIF ALI ALZHRANI',
        nameEn: 'NAIF ALI ALZHRANI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '5F',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'F4G5H6': {
        name: 'NAIF HAMMAD MUSALLAM ALNEMARI',
        nameEn: 'NAIF HAMMAD MUSALLAM ALNEMARI',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '6F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'I7J8K9': {
        name: 'NAIF RABI AL ARISHI',
        nameEn: 'NAIF RABI AL ARISHI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '7F',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'L0M1N2': {
        name: 'NAIF SALEH FARAJ ALHARBI',
        nameEn: 'NAIF SALEH FARAJ ALHARBI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '8F',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'O3P4Q5': {
        name: 'NAJAH NOURI AHMED SALEM',
        nameEn: 'NAJAH NOURI AHMED SALEM',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '9F',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R6S7T8': {
        name: 'NAQAA TURKI SALEM ALHARTHI',
        nameEn: 'NAQAA TURKI SALEM ALHARTHI',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '11F',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'U9V0W1': {
        name: 'NASHMI ATALLH AL JU',
        nameEn: 'NASHMI ATALLH AL JU',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '12D',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'X2Y3Z4': {
        name: 'NAWAF KHALED ALHOMAYANI',
        nameEn: 'NAWAF KHALED ALHOMAYANI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '13D',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A5B6C7': {
        name: 'NOUF LUWAYFI ALHAMDI',
        nameEn: 'NOUF LUWAYFI ALHAMDI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '14F',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'D8E9F0': {
        name: 'NOURA OUDAH MOHAMMED AL-BALAWI',
        nameEn: 'NOURA OUDAH MOHAMMED AL-BALAWI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '15A',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'G1H2I3': {
        name: 'QAMAR MOHSEN ALKHAMALI',
        nameEn: 'QAMAR MOHSEN ALKHAMALI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '16A',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'J4K5L6': {
        name: 'RAGHAD IBRAHIM ABDULLAH ALKHAIBARI',
        nameEn: 'RAGHAD IBRAHIM ABDULLAH ALKHAIBARI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '17E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'M7N8O9': {
        name: 'RAGHAD THAMER SHNAN ALZHRANI',
        nameEn: 'RAGHAD THAMER SHNAN ALZHRANI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '18C',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'P0Q1R2': {
        name: 'RAED BANDAR SAEED ALSAUD',
        nameEn: 'RAED BANDAR SAEED ALSAUD',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '19F',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'S3T4U5': {
        name: 'RAED MAJED KONKAR',
        nameEn: 'RAED MAJED KONKAR',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '20E',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'V6W7X8': {
        name: 'RAHAF BANDAR ATI ALHARBI',
        nameEn: 'RAHAF BANDAR ATI ALHARBI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '21F',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Y9Z0A1': {
        name: 'RAHAF MOHAMMED ABDULLAH ALASMARI',
        nameEn: 'RAHAF MOHAMMED ABDULLAH ALASMARI',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '22D',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'B2C3D4': {
        name: 'RAHAF SALEEM ALHAWITI',
        nameEn: 'RAHAF SALEEM ALHAWITI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '23D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E5F6G7': {
        name: 'RAHAF SALEH ALOUFI',
        nameEn: 'RAHAF SALEH ALOUFI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '24F',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'H8I9J0': {
        name: 'RAWAN HAMAD ALI ALQARNI',
        nameEn: 'RAWAN HAMAD ALI ALQARNI',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '25D',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'K1L2M3': {
        name: 'RAWAN MOHAMMED HASSAN ALMUNTASHIRI',
        nameEn: 'RAWAN MOHAMMED HASSAN ALMUNTASHIRI',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '26D',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'N4O5P6': {
        name: 'REEMA AHMAD SALIM ALATAWI',
        nameEn: 'REEMA AHMAD SALIM ALATAWI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '27D',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Q7R8S9': {
        name: 'REEMA ATYAH AL-ALWANI',
        nameEn: 'REEMA ATYAH AL-ALWANI',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '28D',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'T0U1V2': {
        name: 'REMAS HAMED ALSULIMANI',
        nameEn: 'REMAS HAMED ALSULIMANI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '29D',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'W3X4Y5': {
        name: 'REMAS OMAR ALI ZAILA',
        nameEn: 'REMAS OMAR ALI ZAILA',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '30D',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Z6A7B8': {
        name: 'RENAD SALEM ALJOHANI',
        nameEn: 'RENAD SALEM ALJOHANI',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '1C',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'C9D0E1': {
        name: 'RIFAL KHALID ALSELAMI',
        nameEn: 'RIFAL KHALID ALSELAMI',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '2C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'F2G3H4': {
        name: 'RITAL MOHAMMED ABUALJADAIL',
        nameEn: 'RITAL MOHAMMED ABUALJADAIL',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '3A',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'I5J6K7': {
        name: 'RUWAYD NAIF AYED ALMGHAMISI',
        nameEn: 'RUWAYD NAIF AYED ALMGHAMISI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '4F',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'L8M9N0': {
        name: 'SAUD OMAR ALQARNI',
        nameEn: 'SAUD OMAR ALQARNI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '5A',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        specialAssistance: 'wheelchair'
    },
    'O1P2Q3': {
        name: 'SAYIL MASAD SALIH AL-JOHANI',
        nameEn: 'SAYIL MASAD SALIH AL-JOHANI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '6C',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'R4S5T6': {
        name: 'SARAH MAJED SALEM ALHARBI',
        nameEn: 'SARAH MAJED SALEM ALHARBI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '7A',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'U7V8W9': {
        name: 'SARAH MAHMOUD ALJOHANI',
        nameEn: 'SARAH MAHMOUD ALJOHANI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '8D',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'X0Y1Z2': {
        name: 'SARAH SALEH M ALHARBI',
        nameEn: 'SARAH SALEH M ALHARBI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '9A',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A3B4C5': {
        name: 'SHAHAAD ABDULHAKEEM ALASAL',
        nameEn: 'SHAHAAD ABDULHAKEEM ALASAL',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '10C',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'D6E7F8': {
        name: 'SHAIMA GHAZI MUSTAFA HOWLADAR',
        nameEn: 'SHAIMA GHAZI MUSTAFA HOWLADAR',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '11C',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'G9H0I1': {
        name: 'SHAIMAA HASEN HUSAIN ALSAHAFI',
        nameEn: 'SHAIMAA HASEN HUSAIN ALSAHAFI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '12A',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'J2K3L4': {
        name: 'SHATHA ABDULRAHMAN ALGAMDI',
        nameEn: 'SHATHA ABDULRAHMAN ALGAMDI',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '13C',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'M5N6O7': {
        name: 'SHURUQ AHMED MUSALLAM ALBALAWI',
        nameEn: 'SHURUQ AHMED MUSALLAM ALBALAWI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '14A',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'P8Q9R0': {
        name: 'SHORUQ SALEH MOHAMMED ALSHEHRI',
        nameEn: 'SHORUQ SALEH MOHAMMED ALSHEHRI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '15B',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'S1T2U3': {
        name: 'SULAFA HAMIED ALJOHANI',
        nameEn: 'SULAFA HAMIED ALJOHANI',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '16C',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'V4W5X6': {
        name: 'SULAIMAN FAISAL AL-MUQATI',
        nameEn: 'SULAIMAN FAISAL AL-MUQATI',
        flight: 'SV723',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'نجران',
        destinationEn: 'Najran',
        gate: 'C21',
        seat: '17A',
        departure: '15:55',
        arrival: '17:25',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'Y7Z8A9': {
        name: 'TAHANI SELMI JABER ALHUBAYSHI',
        nameEn: 'TAHANI SELMI JABER ALHUBAYSHI',
        flight: 'SV834',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الطائف',
        destinationEn: 'Taif',
        gate: 'A05',
        seat: '18D',
        departure: '10:30',
        arrival: '11:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'B0C1D2': {
        name: 'TALA AHMAD BAKR AQEEL',
        nameEn: 'TALA AHMAD BAKR AQEEL',
        flight: 'SV456',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '19B',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E3F4G5': {
        name: 'TETHKAR ALHUMAIDI ALENAZI',
        nameEn: 'TETHKAR ALHUMAIDI ALENAZI',
        flight: 'SV189',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '20B',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'H6I7J8': {
        name: 'THIKRA FAISAL ALHARBI',
        nameEn: 'THIKRA FAISAL ALHARBI',
        flight: 'SV345',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '21B',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'K9L0M1': {
        name: 'TURKI ABDULLAH DAKHIL ALSALDALANL',
        nameEn: 'TURKI ABDULLAH DAKHIL ALSALDALANL',
        flight: 'SV678',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'سكاكا',
        destinationEn: 'Sakaka',
        gate: 'C14',
        seat: '22E',
        departure: '14:15',
        arrival: '16:05',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'N2O3P4': {
        name: 'TURKI ALI ABDULLAH ALAMRI',
        nameEn: 'TURKI ALI ABDULLAH ALAMRI',
        flight: 'SV234',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '23E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Q5R6S7': {
        name: 'TURKI HAMOUD HMAED ALHAMDI',
        nameEn: 'TURKI HAMOUD HMAED ALHAMDI',
        flight: 'SV512',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'خميس مشيط',
        destinationEn: 'Khamis Mushait',
        gate: 'B19',
        seat: '24E',
        departure: '11:50',
        arrival: '13:20',
        terminal: '1',
        class: 'درجة رجال أعمال',
        classEn: 'Business Class',
        baggageAllowance: { count: 3, weight: 23 }
    },
    'T8U9V0': {
        name: 'TURKY IBRAHEEM ALI ALASERI',
        nameEn: 'TURKY IBRAHEEM ALI ALASERI',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '25E',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'W1X2Y3': {
        name: 'WAAD MUASLLAM ALWABISI',
        nameEn: 'WAAD MUASLLAM ALWABISI',
        flight: 'SV623',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'عرعر',
        destinationEn: 'Arar',
        gate: 'C11',
        seat: '26E',
        departure: '16:20',
        arrival: '18:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'Z4A5B6': {
        name: 'WADAN MOHAMMED ALHAWITI',
        nameEn: 'WADAN MOHAMMED ALHAWITI',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '27E',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'C7D8E9': {
        name: 'WAJDAN HALIL AL-QATHAMI',
        nameEn: 'WAJDAN HALIL AL-QATHAMI',
        flight: 'SV356',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الباحة',
        destinationEn: 'Al Bahah',
        gate: 'B16',
        seat: '28E',
        departure: '18:40',
        arrival: '19:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'F0G1H2': {
        name: 'WALEED MOHAMMED ALATAWI',
        nameEn: 'WALEED MOHAMMED ALATAWI',
        flight: 'SV154',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '29E',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'I3J4K5': {
        name: 'WASAN SALEH SALMAN ALBALAWI',
        nameEn: 'WASAN SALEH SALMAN ALBALAWI',
        flight: 'SV287',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '30E',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'L6M7N8': {
        name: 'WED ATIF AHMED SABBAGH',
        nameEn: 'WED ATIF AHMED SABBAGH',
        flight: 'SV412',
        aircraftModel: 'Airbus A321',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'أبها',
        destinationEn: 'Abha',
        gate: 'C15',
        seat: '1F',
        departure: '19:20',
        arrival: '20:45',
        terminal: '1',
        class: 'درجة أولى',
        classEn: 'First Class',
        baggageAllowance: { count: 3, weight: 32 }
    },
    'O9P0Q1': {
        name: 'YASER MARZOUQ AWADH ALHARBI',
        nameEn: 'YASER MARZOUQ AWADH ALHARBI',
        flight: 'SV633',
        aircraftModel: 'Boeing 787 Dreamliner',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'تبوك',
        destinationEn: 'Tabuk',
        gate: 'A07',
        seat: '2F',
        departure: '11:15',
        arrival: '12:50',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 },
        hasGateChange: true
    },
    'R2S3T4': {
        name: 'YASSER MAJDY YASSER ALLAILY',
        nameEn: 'YASSER MAJDY YASSER ALLAILY',
        flight: 'SV789',
        aircraftModel: 'Airbus A330',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'جازان',
        destinationEn: 'Jazan',
        gate: 'B12',
        seat: '3F',
        departure: '13:40',
        arrival: '15:10',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'U5V6W7': {
        name: 'YAZAN DHAIFALAHH ALARAYANI',
        nameEn: 'YAZAN DHAIFALAHH ALARAYANI',
        flight: 'SV156',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الرياض',
        destinationEn: 'Riyadh',
        gate: 'A12',
        seat: '4F',
        departure: '14:30',
        arrival: '16:15',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'X8Y9Z0': {
        name: 'YAZAN MOHAMMED AHMED BAOTHMAN',
        nameEn: 'YAZAN MOHAMMED AHMED BAOTHMAN',
        flight: 'SV445',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'حائل',
        destinationEn: 'Hail',
        gate: 'C09',
        seat: '5F',
        departure: '17:25',
        arrival: '18:55',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'A1B2C3D': {
        name: 'YUNUS SAAD AL-RIFAI',
        nameEn: 'YUNUS SAAD AL-RIFAI',
        flight: 'SV298',
        aircraftModel: 'Boeing 777',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'الدمام',
        destinationEn: 'Dammam',
        gate: 'B08',
        seat: '6F',
        departure: '16:45',
        arrival: '18:20',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    },
    'E4F5G6H': {
        name: 'YOUSEF SALEH HAMOUD ALJOUFI',
        nameEn: 'YOUSEF SALEH HAMOUD ALJOUFI',
        flight: 'SV567',
        aircraftModel: 'Airbus A320',
        origin: 'جدة',
        originEn: 'Jeddah',
        destination: 'القصيم',
        destinationEn: 'Qassim',
        gate: 'A18',
        seat: '7F',
        departure: '12:10',
        arrival: '13:35',
        terminal: '1',
        class: 'اقتصادية',
        classEn: 'Economy',
        baggageAllowance: { count: 2, weight: 23 }
    }
};

export const occupiedSeatsForFlight = [
    '12B', '15A', '8C', '22D', '5B', '18E', '11C', '25F', '14A', '9B', '7C', '20A', '16B', '13E', '21C', '19A', '6A', '17B', '10D', '23C', '4A', '24B', '10A', '3B', '1A'
];


export function findPassenger(bookingRef: string, name: string) {
    const passenger = passengerDatabase[bookingRef.toUpperCase()];
    if (passenger && passenger.nameEn.toUpperCase() === name.toUpperCase()) {
        return passenger;
    }
    return null;
}
